### ISSUE TITLE
MouseOverDictionary.exe が起動できない。

### ISSUE THREAD

**Issue by synctam** [kengo700/mouse_over_dictionary#1]
### 状況
MouseOverDictionary.ver.0.0.1.zip を解凍し実行したところ、何も表示されずにプロセスが終了してしまう。イベントログで確認したところところ、以下のエラーが記録されていた。
```
イベントＩＤ：1000 例外コード： 0xc000001d
障害が発生しているアプリケーション名: QtGuiApplicationTest.exe、バージョン: 0.0.0.0、タイム スタンプ: 0x5e194963
障害が発生しているモジュール名: QtGuiApplicationTest.exe、バージョン: 0.0.0.0、タイム スタンプ: 0x5e194963
例外コード: 0xc000001d
障害オフセット: 0x000000000000d2e5
障害が発生しているプロセス ID: 0x34ac
障害が発生しているアプリケーションの開始時刻: 0x01d5c83537806ba2
障害が発生しているアプリケーション パス: C:\Users\xxxxxx\Desktop\QtGuiApplicationTest3\QtGuiApplicationTest.exe
障害が発生しているモジュール パス: C:\Users\xxxxxx\Desktop\QtGuiApplicationTest3\QtGuiApplicationTest.exe
レポート ID: 427462e5-2276-4851-84e6-f253c77eac20
障害が発生しているパッケージの完全な名前: 
障害が発生しているパッケージに関連するアプリケーション ID: 
```

### 環境
Windows 10 Pro(x64) バージョン 1909
![CPU-Z  - 2020 01 11_13 48 23_001](https://user-images.githubusercontent.com/17960105/72199014-1f5b8480-3479-11ea-97f4-1c8b167326dc.jpg)

**Comment by kengo700** [comment]
TesseractがAVX2というCPU機能を使おうとすることが原因だった。AVX2対応CPUのPCでビルドしたものを配布したため、非対応のCPUではクラッシュしていた。

v0.0.1ではvcpkgでビルドしていたが、下記ページの方法でビルドし直したところ解決した。
https://github.com/charlesw/tesseract/wiki/Compiling-Tesseract-and-Libleptonica-(using-vcpkg)

ビルドし直しの手順メモ
1. 念のためコントロールパネルからシステムロケールを英語にして再起動
2. 上記ページの「4. Build Leptonica:」の手順でビルド
    * ビルド作業は「C:\tesseract」の中で行った
    * ただしVisual Studio 2017にしたので、vs16-xはvs15-xに、"Visual Studio 16 2019"は"Visual Studio 15 2017"に
3. 上記ページの「5. Build Tesseract:」の手順でビルド
    * ただし同ページの「Disabling AVX optimisations」の通りに「設定なし」にしてAVX2等の使用をオフに
4. vcpkgバージョンのTesseractが組み込まれないように、念のためvcpkgで「vcpkg integrate remove」
5. システムロケールを日本語に戻して再起動
6. MouseOverDictionary.slnをVisual Studio 2017で開き、下記のプロパティを設定
    * 追加のインクルードディレクトリ：C:\tesseract\build\x64\include
    * 追加のライブラリディレクトリ：C:\tesseract\build\x64\lib
    * 追加の依存ファイル：tesseract41.lib;leptonica-1.78.0.lib
7. MouseOverDictionaryをビルド後、Releaseフォルダに下記ファイルをコピー
    * C:\tesseract\build\x64\bin\tesseract41.dll
    * C:\tesseract\build\x64\bin\leptonica-1.78.0.dll
