### ISSUE TITLE
Idle時のパフォーマンスの改善について

### ISSUE THREAD

**Issue by synctam** [kengo700/mouse_over_dictionary#2]
## 状況 ##
Mouse Over Dictionaryを起動すると、Idle時（マウスを動かしていないとき）でもCPU利用率が 20～25% となってしまう。

## 要望 ##
Idle時のCPU利用率を削減して欲しい。

## 環境 ##
OS:Windows 10 Pro(64bit) バージョン 1909 
プロセッサ：ADM A10-6700 APU

### Sleep()関数を使用した場合 ### 
試しに、thread.cpp の While()ループ内の全ての continue の前に Sleep(1)を挿入し待機させたところ、Idle時のCPU利用率をゼロに抑えることができました。しかし、この方式ですと Windows API を使用し強制的にコンテキストスイッチを発生させているため処理系に依存してしまいます。できれば、処理方式をWhileループではなくスレッドにシグナルを送る方式に変更された方が良いかもしれません。

**Comment by kengo700** [comment]
ご指摘ありがとうございます！ アイドル時にCPU利用率が上がるのは私のミスです。ひとまずSleepを入れる方法で対処します。

「Windows API を使用し強制的にコンテキストスイッチを発生させているため処理系に依存」の部分が理解できないため、もう少し詳しく教えていただけますか？

スレッドにシグナルを送る方式については、確か以前試行錯誤していた時に、ウィンドウ内でしかマウス移動のシグナルを取れなかったような覚えがあります。ただQtを全く分かっていなかった時のことなので、もう一度調べてみます。

**Comment by synctam** [comment]
「処理系に依存」とはWindows以外ではSleep(1)が使えないと思いこう書きました。Windows以外でこのツールを動作させる予定がないのであれば、Sleep(1)でも良いと思います。

詳しくないのですが、自分の場合、昔からの経験則からこのような場合は Sleep(1) でごまかしていました。
Windows では、Sleep(1) を実行するとOSが他のスレッドに制御を渡し、スレッドは眠ります。そしてOSの次のタイムスライスのスケージュール時にこのスレッドを起こします。結果的に、このプロセスのCPU利用率が低下することになります。
なお、次のようなQtTimerのSleepでは、CPU利用率の削減はできませんでした。

```QTimer::singleShot(1, this, SLOT(quit()));```

それと、シグナルについてもよく知らないのですが、mouse_over_dictionary.cpp のマウス移動イベント（MouseOverDictionary::moveEvent() ここかな？）からスレッドにシグナルを送ればよいのではないかと思い書きました。

**Comment by kengo700** [comment]
なるほど、大体理解できました。ありがとうございます。他プラットフォームへの移植は今のところ考えていないので、Sleep(1)による対策で行こうと思います。

MouseOverDictionary::moveEvent()はウィンドウの移動イベントですね。下記ページなどを見る限り、やはり基本的にウィンドウ外でのマウス移動イベントを取得するのは難しいようですが、時間がある時に試してみます。
https://stackoverflow.com/questions/8520183/how-can-i-receive-or-be-able-to-process-mousemoveevents-outside-my-widget-wind

**Comment by synctam** [comment]
仰るとおりマウスイベントは自フォーム上のみでした、失礼しました。

**Comment by synctam** [comment]
待機時の問題は解決され、とても使いやすくなりました。
対応ありがとうございました。
