### ISSUE TITLE
ウィンドウの透明度について

### ISSUE THREAD

**Issue by synctam** [kengo700/mouse_over_dictionary#5]
## 現状 ##
ウィンドウの透明度は固定となっています。

## 要望 ##
設定でメインウィンドウ、ミニウィンドウの透明度をそれぞれ指定できるようにして欲しい。

ご検討いただければ幸いです。

**Comment by kengo700** [comment]
ご提案ありがとうございます！ settings.iniで指定する方法であればすぐに実現できそうです。

**Comment by kengo700** [comment]
v0.0.5で実装しました！

**Comment by synctam** [comment]
機能の実装を確認しました。
早速の対応ありがとうございました。
