### ISSUE TITLE
メインウィンドウの位置とサイズについて

### ISSUE THREAD

**Issue by synctam** [kengo700/mouse_over_dictionary#6]
## 現状 ##
ウィンドウのサイズは固定で、位置は起動時にマウスのあるモニターの中央に表示される。

## 要望 ##
Mouse Over Dictionary 終了時にメインウィンドウの位置とサイズを保存し、次回起動時はこの設定情報を元にウィンドウを再現して欲しい。

## 検討事項 ##
この仕様を採用した時の副作用は、存在しなくなったモニター側にウィンドウが表示されてしまう可能性があることです。例えば、モニターＡ,Ｂの２つのモニターを使用している場合、前回モニターＢで Mouse Over Dictionary を終了した後、モニターＢを撤去または電源をオフにした場合、次回起動時、使用していないモニターＢにメインウィンドウが表示されてしまい、面倒なことになります。
この場合、タスクバーを Shift+右クリックし、[移動]を選び、キーボードでウィンドウ位置を調整することになります。もし、タスクトレイの実装が予定されているのであれば、タスクトレイアイコンのメニューからウィンドウ位置を調整する方法が考えられます。

ご検討いただければ幸いです。

**Comment by kengo700** [comment]
終了時のウィンドウの情報の保存と起動時に読み込みも、settings.iniで指定する方法であればすぐに実現できそうです。

ウィンドウが範囲外に移動してしまった場合は、ひとまずはご提案の方法で対処してもらうことにしましょう。

別の方法として、settings.iniファイルの該当項目を削除した場合はデフォルト値が使われるので、それで起動時のウィンドウ位置設定のリセットが可能だと思います。

もしQtの機能でスクリーン領域の情報が取得できるなら、領域外であればデフォルト値を使う処理を入れれば防げるかもしれません。

**Comment by kengo700** [comment]
v0.0.5で実装しました！

スクリーンの範囲外に出てしまった場合については、他のソフトでも対応しているものは少なそうなので、既存の方法で対応してもらうことにします。
https://www.atmarkit.co.jp/ait/articles/0312/06/news006.html

**Comment by synctam** [comment]
機能の実装を確認しました。
確かに他のソフトで範囲外の対応は見たことがないですね。
手動により対応で構わないと思います。
早速の対応ありがとうございました。
